<?php
namespace Laventure\Component\Database\ORM\Persistence\Manager;

use Laventure\Component\Database\Builder\QueryBuilder as Builder;
use Laventure\Component\Database\Builder\SQL\Commands\DQL\Select;


class QueryBuilder
{

    /**
     * @var EntityManager
    */
    protected EntityManager $em;



    /**
     * @param EntityManager $em
    */
    public function __construct(EntityManager $em)
    {
         parent::__construct($em->getConnection(), '');
    }





    /**
     * @param string|null $selects
     *
     * @param bool $distinct
     *
     * @return Select
    */
    public function select(string $selects = null, bool $distinct = false): Select
    {
         return parent::select($selects, $distinct); // TODO: Change the autogenerated stub
    }
}